name: Test create release from template

on:
  workflow_dispatch:
  
env:
  CDRO_TOKEN: ${{ secrets.CDRO_TOKEN }}
  CDRO_URL: ${{ secrets.CDRO_URL }}

jobs: 
  start-release-job:
    runs-on: ubuntu-latest
    steps:
       
      - name: Create project if needed
        uses: cloudbees-actions/eval-dsl@v1
        with:
          dsl: project "GHA Test"
            
      - name: Create release
        uses: cloudbees-actions/create-release-from-template@v1
        with:
          templateProjectName: Electric Cloud
          templateCatalogName: Releases
          templateName: Multi-stage CD Release
          actualParameter: |
            releaseProjectName: GHA Test
            releaseName: GHA Release from template
            releaseDescription: desc
            releaseStartDate: 2023-07-31
            releaseEndDate: 2023-08-02     
      
      - name: Start release
        uses: cloudbees-actions/start-release@v1
        with:
          projectName: GHA Test
          releaseName: GHA Release from template
