name: Test run-procedure action

on:
  workflow_dispatch:
  
env:
  CDRO_TOKEN: ${{ secrets.CDRO_TOKEN }}
  CDRO_URL: ${{ secrets.CDRO_URL }}

jobs: 
  run-procedure-job:
    runs-on: ubuntu-latest
    steps:
         
      - name: Create procedure
        uses: cloudbees-actions/eval-dsl@v1
        with:
          dsl: |
            project "GHA Test",{
              procedure "GHA Procedure",{
                formalParameter "Input1"
                formalParameter "Input2"
                formalParameter "Input3", type: "textarea"
              }
            }          
          
      - name: Run procedure
        uses: cloudbees-actions/run-procedure@v1
        with:
          projectName: GHA Test
          procedureName: GHA Procedure
          actualParameter: |
            Input1: xyz
            Input2: abc
            Input3: "line1\nline2"
