name: 'Test EvalDSL with resolved/unresolved SSL'

on:
  workflow_dispatch:

jobs:
  eval-with-resolved-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Run EvalDSL Action
        uses: cloudbees-github-actions/eval-dsl@v1
        env:
          CDRO_TOKEN: ${{ secrets.CDRO_TOKEN }}
          CDRO_URL: ${{ secrets.CDRO_URL }}
        with:
          dsl: getProjects()

  eval-with-unresolved-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Run EvalDSL Action
        uses: cloudbees-github-actions/eval-dsl@v1
        env:
          CDRO_TOKEN: ${{ secrets.TEST_UNIVERSITY_TOKEN }}
          CDRO_URL: ${{ secrets.TEST_UNIVERSITY_URL }}
        with:
          ignore-unverified-cert: true
          dsl: getProjects()
